#!/bin/sh
for f in ./config.*; do
    rm -f $f
done
if [ -e confdefs.h ]; then
    rm -f confdefs.h
fi
if [ -e src/Makevars ]; then
    rm -f src/Makevars
fi
if [ -e autom4te.cache ]; then
    rm -rf autom4te.cache
fi
for f in src/*.o src/*.so; do
    rm -f $f
done
find . -name \*~ | xargs rm -f
#rm -vf configure 
rm -vf config.log config.status
exit 0
