#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/*
  generated by tools::package_native_routine_registration_skeleton(".")
*/

/* .C calls */
extern void bayesCox(void *, void *, void *, void *, void *, void *, void *,
                     void *, void *, void *, void *, void *, void *, void *,
                     void *, void *, void *, void *, void *, void *, void *,
                     void *, void *, void *, void *, void *, void *);

static const R_CMethodDef CEntries[] = {
    {"bayesCox", (DL_FUNC) &bayesCox, 27},
    {NULL, NULL, 0}
};

void R_init_dynsurv(DllInfo *dll)
{
    R_registerRoutines(dll, CEntries, NULL, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
